# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sensationprotocol.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sensationprotocol.proto',
  package='sensationdriver',
  serialized_pb='\n\x17sensationprotocol.proto\x12\x0fsensationdriver\"\xa5\x01\n\tSensation\x12\x31\n\x06region\x18\x01 \x02(\x0e\x32!.sensationdriver.Sensation.Region\x12\x13\n\x0b\x61\x63tor_index\x18\x02 \x02(\x05\x12\x11\n\tintensity\x18\x03 \x02(\x02\"=\n\x06Region\x12\r\n\tLEFT_HAND\x10\x00\x12\x10\n\x0cLEFT_FOREARM\x10\x01\x12\x12\n\x0eLEFT_UPPER_ARM\x10\x02')



_SENSATION_REGION = _descriptor.EnumDescriptor(
  name='Region',
  full_name='sensationdriver.Sensation.Region',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='LEFT_HAND', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LEFT_FOREARM', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LEFT_UPPER_ARM', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=149,
  serialized_end=210,
)


_SENSATION = _descriptor.Descriptor(
  name='Sensation',
  full_name='sensationdriver.Sensation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='region', full_name='sensationdriver.Sensation.region', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='actor_index', full_name='sensationdriver.Sensation.actor_index', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='intensity', full_name='sensationdriver.Sensation.intensity', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SENSATION_REGION,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=45,
  serialized_end=210,
)

_SENSATION.fields_by_name['region'].enum_type = _SENSATION_REGION
_SENSATION_REGION.containing_type = _SENSATION;
DESCRIPTOR.message_types_by_name['Sensation'] = _SENSATION

class Sensation(_message.Message, metaclass=_reflection.GeneratedProtocolMessageType):
  DESCRIPTOR = _SENSATION

  # @@protoc_insertion_point(class_scope:sensationdriver.Sensation)


# @@protoc_insertion_point(module_scope)
